DECLARE @LOTVOU BIGINT, @CMPVOU BIGINT, @COILNO VARCHAR(30), @MCOILNO VARCHAR(30) 
DECLARE @LOTVOU1 BIGINT, @CMPVOU1 BIGINT, @COILNO1 VARCHAR(30), @MCOILNO1 VARCHAR(30), @GRADE1 VARCHAR(50), @GRDVOU1 BIGINT, @HEATNO1 VARCHAR(50), @OD1 DECIMAL(18,2)
DECLARE XCUR CURSOR FOR SELECT JOTCMPVOU, JOTVOU FROM JOBTRN WHERE JOTJOBVOU = 19 ORDER BY JOTRECCOILNO
OPEN XCUR
FETCH NEXT FROM XCUR INTO @CMPVOU, @LOTVOU
WHILE (@@FETCH_STATUS=0)
BEGIN
	UPDATE JOBTRN SET JOTCMPVOU = @CMPVOU WHERE JOTVOU = @LOTVOU
	FETCH NEXT FROM XCUR INTO @CMPVOU, @LOTVOU
END
CLOSE XCUR
DEALLOCATE XCUR

