
DECLARE @LOTVOU BIGINT, @CMPVOU BIGINT, @COILNO VARCHAR(30), @SUPCOILNO VARCHAR(30), @GRADE VARCHAR(30), @GRDVOU BIGINT, @PVOU BIGINT, @PRDVOU BIGINT, @QTY DECIMAL(18,2), @ACCVOU BIGINT,
		@THICK DECIMAL(18,2), @WIDTH DECIMAL(18,2), @OD DECIMAL(18,2), @HEATNO VARCHAR(30)
DECLARE @LOTVOU1 BIGINT, @CMPVOU1 BIGINT, @COILNO1 VARCHAR(30), @SUPCOILNO1 VARCHAR(30), @GRADE1 VARCHAR(30), @GRDVOU1 BIGINT, @PVOU1 BIGINT, @PRDVOU1 BIGINT, @QTY1 DECIMAL(18,2),@ACCVOU1 BIGINT,
		@THICK1 DECIMAL(18,2), @WIDTH1 DECIMAL(18,2), @OD1 DECIMAL(18,2), @PRVCOILNO VARCHAR(30)='', @HEATNO1 VARCHAR(30)
DECLARE XCUR CURSOR FOR SELECT LOTCMPVOU, LOTVOU, LOTCOILNO, LOTSUPCOILNO, LOTPRDVOU, LOTGRADE, LOTGRDMSCVOU, LOTTHICK, LOTWIDTH, LOTOD, LOTHEATNO, LOTQTY FROM LOTMST WHERE LOTMCOILNO IN ('196364') ORDER BY LOTCOILNO
OPEN XCUR
FETCH NEXT FROM XCUR INTO @CMPVOU, @LOTVOU, @COILNO, @SUPCOILNO, @PRDVOU, @GRADE, @GRDVOU, @THICK, @WIDTH, @OD, @HEATNO, @QTY
WHILE (@@FETCH_STATUS=0)
BEGIN
	IF @PRVCOILNO <> @COILNO BEGIN

		DECLARE YCUR CURSOR FOR SELECT LOTCMPVOU, LOTVOU, LOTCOILNO, LOTSUPCOILNO, LOTPRDVOU, LOTGRADE, LOTGRDMSCVOU, LOTTHICK, LOTWIDTH, LOTOD, LOTHEATNO, LOTQTY  FROM LOTMST WHERE LOTMCOILNO = @COILNO ORDER BY LOTDT, LOTVOU 
		OPEN YCUR
		FETCH NEXT FROM YCUR INTO @CMPVOU1, @LOTVOU1, @COILNO1, @SUPCOILNO1, @PRDVOU1, @GRADE1, @GRDVOU1, @THICK1, @WIDTH1, @OD1, @HEATNO1, @QTY1
		WHILE (@@FETCH_STATUS=0)
		BEGIN
			--SELECT @COILNO1, @SUPCOILNO1, @PRDVOU1, @GRADE1, @GRDVOU1, @THICK, @WIDTH, @OD, @SUPCOILNO, @PRDVOU, @GRADE, @GRDVOU, @THICK, @WIDTH, @OD
			IF @HEATNO <> @HEATNO1
				UPDATE LOTMST SET LotHeatNo = @HEATNO WHERE LOTVOU = @LOTVOU1
			FETCH NEXT FROM YCUR INTO @CMPVOU1, @LOTVOU1, @COILNO1, @SUPCOILNO1, @PRDVOU1, @GRADE1, @GRDVOU1, @THICK1, @WIDTH1, @OD1, @HEATNO1, @QTY1
		END
		CLOSE YCUR
		DEALLOCATE YCUR
	END
	SET @PRVCOILNO = @COILNO

	FETCH NEXT FROM XCUR INTO @CMPVOU, @LOTVOU, @COILNO, @SUPCOILNO, @PRDVOU, @GRADE, @GRDVOU, @THICK, @WIDTH, @OD, @HEATNO, @QTY
END
CLOSE XCUR
DEALLOCATE XCUR

