Declare @JotVou bigint, @Cmpvou int
DECLARE XCUR CURSOR FOR SELECT JOTVOU, JOTCMPVOU FROM JOBTRN WHERE JOTJOBVOU = 53 ORDER BY JOTRECCOILNO
OPEN XCUR
FETCH NEXT FROM XCUR INTO @JOTVOU, @CMPVOU
WHILE (@@FETCH_STATUS=0)
BEGIN
	UPDATE JOBTRN SET JOTCMPVOU = @CMPVOU WHERE JOTVOU = @JOTVOU
	FETCH NEXT FROM XCUR INTO @JOTVOU, @CMPVOU
END
CLOSE XCUR
DEALLOCATE XCUR
